apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/5 * * * * "
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: nginx
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello world!
          restartPolicy: OnFailure
